### ISSUE TITLE
Launch script from a different directory?

### ISSUE THREAD

**Issue by twfarley** [ajbowler/mlb-led-scoreboard#27]
I was trying to add the python script to launch on boot but it doesn't work unless I'm in the mlb-led directory. For example:

$ sudo python ~/mlb-led-scoreboard/main.py -r

Traceback (most recent call last):
  File "/home/pi/mlb-led-scoreboard/main.py", line 33, in <module>
    render_games(matrix, canvas, games[0], args)
  File "/home/pi/mlb-led-scoreboard/renderer.py", line 30, in render_games
    success = __refresh_scoreboard(canvas, game)
  File "/home/pi/mlb-led-scoreboard/renderer.py", line 89, in __refresh_scoreboard
    renderer = ScoreboardRenderer(canvas, scoreboard)
  File "/home/pi/mlb-led-scoreboard/scoreboard_renderer.py", line 9, in __init__
    self.colors = json.load(open('Assets/colors.json'))
IOError: [Errno 2] No such file or directory: 'Assets/colors.json'

**Comment by ajbowler** [comment]
I've got an idea in mind to get this working.

**Comment by twfarley** [comment]
Awesome! Thanks! I’ll test this over the weekend.
